import './scss/style.scss';
// import './js/string.js';
// import './js/array.js';
// import './js/map.js';
// import './js/set.js';
// import './js/object.js';
// import './js/function.js';
// import './js/operators.js';
// import './js/error.js';
// import './js/instruction.js';
// import './js/cycles.js';